android-tools-conf: remove PACKAGE_ARCH = MACHINE_ARCH
Source: meta-clang
MR: 125084
Type: Integration
Disposition: Merged from meta-clang
ChangeID: bd4c6b9d5d57e1868774088f272d9b07c49a7f99
Description:

android-tools inherits the native class, and RDEPENDS on android-tools-conf.
This line causes an error when trying to build android-tools-native:

"""
ERROR: Required build target 'android-tools-native' has no buildable providers.
Missing or unbuildable dependency chain was: ['android-tools-native', 'clang-native-x86_64']
"""

Signed-off-by: Etienne Cordonnier <ecordonnier@snap.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>