bpftrace: move from dynamic-layers/openembedded-layer to dynamic-layers/meta-python
Source: meta-clang
MR: 23460
Type: Integration
Disposition: Merged from meta-clang
ChangeID: 525625cb266c8a6ea9a4ddedabf935c825d38510
Description:

* bpftrace itself doesn't depend on meta-python, but
  bpftrace from dynamic-layers/openembedded-layer depends on bcc from dynamic-layers/meta-python
  so better to move it there. This way both bcc and bpftrace are either both available
  at the same time or neither of them.

* fixes https://github.com/kraj/meta-clang/issues/985

  ERROR: Nothing PROVIDES 'bcc' (but /mnt/secondary/poky/meta-clang/dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.20.1.bb DEPENDS on or otherwise requires it). Close matches:
    bc
    byacc
  NOTE: Runtime target 'bpftrace' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['bpftrace', 'bcc']
  ERROR: Required build target 'core-image-minimal' has no buildable providers.
  Missing or unbuildable dependency chain was: ['core-image-minimal', 'bpftrace', 'bcc']

  when only openembedded-layer (meta-oe) is in BBLAYERS and meta-python isn't.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>

Signed-off-by: Archana Polampalli <archana.polampalli@windriver.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>